#!/bin/bash

XPI=rss.xpi

# Replace this value to push to different release channels.
ANDROID_APP_ID=org.mozilla.fennec_leibovic

zip $XPI bootstrap.js \
         install.rdf \
         README.md

# TODO: Make sure this does not suck with spaces in filenames.
adb push "$XPI" /sdcard/"$XPI" && \
# via https://github.com/ncalexan/healthreport-upload-test-addon/blob/master/build.sh
adb shell am start -a android.intent.action.VIEW \
                   -c android.intent.category.DEFAULT \
                   -d file:///mnt/sdcard/"$XPI" \
                   -n $ANDROID_APP_ID/.App && \
echo Pushed $XPI to $ANDROID_APP_ID
